import Link from "next/link";
import { mockStories } from "@/data/mockStory";

export const metadata = {
  title: "Story Tree — Stories",
};

export default function StoryIndexPage() {
  return (
    <main className="min-h-screen bg-page px-6 py-16 text-text-primary sm:px-12">
      <section className="mx-auto flex max-w-5xl flex-col gap-10">
        <header className="flex flex-col gap-3">
          <p className="text-sm uppercase tracking-[0.35em] text-text-muted">
            Stories
          </p>
          <h1 className="text-4xl font-semibold">Story Tree Archive</h1>
          <p className="max-w-3xl text-base text-text-muted">
            Browse mock story outputs generated by the Story Tree agent. Future
            iterations will pull live data from Supabase and support creating new
            stories.
          </p>
        </header>
        <div className="grid gap-4 sm:grid-cols-2">
          {mockStories.map((story) => (
            <Link
              key={story.id}
              href={`/story/${story.id}/constitution`}
              className="group rounded-2xl border border-border bg-surface p-6 shadow-panel transition hover:border-highlight hover:shadow-[0_20px_55px_rgba(9,15,30,0.6)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-highlight"
            >
              <div className="flex items-center justify-between gap-3">
                <h2 className="text-xl font-semibold">{story.title}</h2>
                <span
                  className="h-3 w-3 rounded-full"
                  style={{ backgroundColor: story.accentColor }}
                  aria-hidden="true"
                />
              </div>
              <p className="mt-2 text-sm text-text-muted">
                Authored by {story.author}
              </p>
              <p className="mt-4 text-xs uppercase tracking-[0.3em] text-text-muted/70">
                Open Explorer →
              </p>
            </Link>
          ))}
        </div>
        <div className="rounded-2xl border border-dashed border-border px-6 py-10 text-center text-sm text-text-muted">
          <p className="font-medium text-text-primary">Create New Story</p>
          <p>
            Interactive workflow entry points will appear here once backend APIs
            are wired into the UI.
          </p>
        </div>
      </section>
    </main>
  );
}
