import Link from "next/link";
import { EmptyState } from "@/components/emptyState";
import { getStoryList } from "@/server/data/stories";
import type { StorySummaryViewModel } from "@/server/data/stories";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Story Tree — Stories",
};

export default async function StoryIndexPage() {
  let stories: StorySummaryViewModel[] = [];
  let errorMessage: string | null = null;

  try {
    stories = await getStoryList();
  } catch (error) {
    console.error("Failed to load story list", error);
    if (error instanceof Error && error.name === "SupabaseConfigurationError") {
      errorMessage = error.message;
    } else {
      errorMessage =
        "Unable to load stories from Supabase. Confirm your credentials and try again.";
    }
  }

  const hasStories = stories.length > 0;

  return (
    <main className="min-h-screen bg-page px-6 py-16 text-text-primary sm:px-12">
      <section className="mx-auto flex max-w-5xl flex-col gap-10">
        <header className="flex flex-col gap-3">
          <p className="text-sm uppercase tracking-[0.35em] text-text-muted">
            Stories
          </p>
          <h1 className="text-4xl font-semibold">Story Tree Archive</h1>
          <p className="max-w-3xl text-base text-text-muted">
            Browse story outputs generated by the Story Tree agent. Results load
            directly from Supabase so you can inspect local or remote projects.
          </p>
        </header>
        {hasStories ? (
          <div className="grid gap-4 sm:grid-cols-2">
            {stories.map((story) => (
              <Link
                key={story.id}
                href={`/story/${story.id}/constitution`}
                className="group rounded-2xl border border-border bg-surface p-6 shadow-panel transition hover:border-highlight hover:shadow-[0_20px_55px_rgba(9,15,30,0.6)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-highlight"
              >
                <div className="flex items-center justify-between gap-3">
                  <h2 className="text-xl font-semibold">{story.title}</h2>
                  <span
                    className="h-3 w-3 rounded-full"
                    style={{ backgroundColor: story.accentColor }}
                    aria-hidden="true"
                  />
                </div>
                <p className="mt-2 text-sm text-text-muted">
                  Authored by {story.author}
                </p>
                <p className="mt-4 text-xs uppercase tracking-[0.3em] text-text-muted/70">
                  Open Explorer →
                </p>
              </Link>
            ))}
          </div>
        ) : (
          <EmptyState
            title="No stories available"
            message={
              errorMessage ??
              "Supabase does not have any stories yet. Seed your database with the Story Tree workflow CLI, then refresh this page."
            }
          />
        )}
        <div className="rounded-2xl border border-dashed border-border px-6 py-10 text-center text-sm text-text-muted">
          <p className="font-medium text-text-primary">Create New Story</p>
          <p>
            Interactive workflow entry points will appear here once backend APIs
            are wired into the UI.
          </p>
        </div>
      </section>
    </main>
  );
}
