import Image from "next/image";
import Link from "next/link";
import type { CSSProperties } from "react";
import { EmptyState } from "@/components/emptyState";
import { getStoryList } from "@/server/data/stories";
import type { StorySummaryViewModel } from "@/server/data/stories";
import { storybookPalette } from "@/theme/palette";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Story Tree — Stories",
};

export default async function StoryIndexPage() {
  let stories: StorySummaryViewModel[] = [];
  let errorMessage: string | null = null;

  try {
    stories = await getStoryList();
  } catch (error) {
    console.error("Failed to load story list", error);
    if (error instanceof Error && error.name === "SupabaseConfigurationError") {
      errorMessage = error.message;
    } else {
      errorMessage =
        "Unable to load stories from Supabase. Confirm your credentials and try again.";
    }
  }

  const hasStories = stories.length > 0;

  return (
    <main className="min-h-screen bg-page px-6 py-16 text-text-primary sm:px-12">
      <section className="mx-auto flex max-w-5xl flex-col gap-10">
        <header className="flex flex-col gap-3">
          <p className="text-sm uppercase tracking-[0.35em] text-text-muted">
            Story Tree
          </p>
          <h1 className="text-4xl font-semibold">Interactive Children Stories</h1>
          <p className="max-w-3xl text-base text-text-muted">
            Browse interactive children stories generated by AI. The project is still working in progress.
          </p>
        </header>
        {hasStories ? (
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
            {stories.map((story) => {
              const placeholderStyle: CSSProperties = {
                backgroundImage: `linear-gradient(135deg, ${story.accentColor} 0%, ${storybookPalette.accentMuted} 100%)`,
              };

              return (
                <Link
                  key={story.id}
                  href={`/story/${story.id}/constitution`}
                  className="group flex h-full flex-col overflow-hidden rounded-3xl border border-border bg-page transition hover:bg-surface focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-highlight"
                >
                  <div className="relative aspect-[4/3] w-full overflow-hidden rounded-t-3xl bg-page">
                    {story.thumbnailImagePath ? (
                      <Image
                        src={story.thumbnailImagePath}
                        alt={`${story.title} thumbnail`}
                        fill
                        className="object-cover"
                        sizes="(min-width: 768px) 420px, 100vw"
                      />
                    ) : (
                      <div
                        className="flex h-full w-full flex-col items-center justify-center gap-2 text-center text-[11px] font-medium text-text-muted"
                        style={placeholderStyle}
                      >
                        <span className="text-sm font-semibold text-text-primary">
                          Artwork coming soon
                        </span>
                        <span className="max-w-[14rem] leading-snug text-text-muted">
                          Generate storyboard shots to preview this story.
                        </span>
                      </div>
                    )}
                  </div>
                  <div className="flex flex-1 flex-col gap-3 px-5 py-4">
                    <h2 className="text-xl font-semibold leading-tight text-text-primary">
                      {story.title}
                    </h2>
                    <p className="text-sm leading-relaxed text-text-muted">
                      {story.logline ?? "Logline coming soon."}
                    </p>
                  </div>
                </Link>
              );
            })}
          </div>
        ) : (
          <EmptyState
            title="No stories available"
            message={
              errorMessage ??
              "Supabase does not have any stories yet. Seed your database with the Story Tree workflow CLI, then refresh this page."
            }
          />
        )}
        <div className="rounded-2xl border border-dashed border-border px-6 py-10 text-center text-sm text-text-muted">
          <p className="font-medium text-text-primary">Create New Story</p>
          <p>
            Working in progress. Coming soon.
          </p>
        </div>
      </section>
    </main>
  );
}
